//! `shunt login claude` — import a refreshable Claude Code login or securely
//! store a long-lived token generated by `claude setup-token`.
//!
//! `claude setup-token` is deliberately human-attended and writes no credential
//! file. shunt therefore launches it on the controlling terminal, then asks the
//! operator to paste the resulting token into a hidden prompt. The token is
//! written only to shunt's private account store and is never printed by shunt.

use std::{path::Path, process::Command};

use anyhow::{bail, Context};

use crate::auth::{claude_auth, claude_store};

pub fn run(name: &str, long_lived: bool) -> anyhow::Result<()> {
    claude_store::validate_account_name(name)?;
    let path = if long_lived {
        run_setup_token(name)?
    } else {
        import_current_login(name)?
    };
    println!(
        "Claude account {name:?} saved to {}. Add a name-only account entry to use it.",
        path.display()
    );
    Ok(())
}

fn import_current_login(name: &str) -> anyhow::Result<std::path::PathBuf> {
    let source = claude_auth::default_credentials_path();
    claude_store::import_credentials(name, &source).with_context(|| {
        format!(
            "failed to import {}; run `claude auth login` first, or use `shunt login claude --name {name} --long-lived`",
            source.display()
        )
    })
}

fn run_setup_token(name: &str) -> anyhow::Result<std::path::PathBuf> {
    let claude = find_claude_cli()?;
    println!(
        "Starting `claude setup-token`. Complete its browser flow and copy the token it prints."
    );
    let status = Command::new(&claude)
        .arg("setup-token")
        .status()
        .with_context(|| format!("failed to start {}", claude.display()))?;
    if !status.success() {
        bail!("`claude setup-token` failed with {status}");
    }

    let token = rpassword::prompt_password("Paste the generated token (input hidden): ")
        .context("failed to read setup token")?;
    claude_store::store_setup_token(name, &token)
}

fn find_claude_cli() -> anyhow::Result<std::path::PathBuf> {
    find_executable("claude", std::env::var_os("PATH").as_deref()).ok_or_else(|| {
        anyhow::anyhow!(
            "Claude CLI not found in PATH; install Claude Code, then run `shunt login claude --name <name> --long-lived` again"
        )
    })
}

fn find_executable(command: &str, path: Option<&std::ffi::OsStr>) -> Option<std::path::PathBuf> {
    let path = path?;
    std::env::split_paths(path)
        .map(|directory| directory.join(command))
        .find(|candidate| is_executable(candidate))
}

#[cfg(unix)]
fn is_executable(path: &Path) -> bool {
    use std::os::unix::fs::PermissionsExt;
    path.metadata()
        .is_ok_and(|metadata| metadata.is_file() && metadata.permissions().mode() & 0o111 != 0)
}

#[cfg(not(unix))]
fn is_executable(path: &Path) -> bool {
    path.is_file()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{fs, time::SystemTime};

    #[test]
    fn finds_executable_and_ignores_non_executable_file() {
        let root = std::env::temp_dir().join(format!(
            "shunt-claude-login-{}-{}",
            std::process::id(),
            SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .unwrap()
                .as_nanos()
        ));
        let first = root.join("first");
        let second = root.join("second");
        fs::create_dir_all(&first).unwrap();
        fs::create_dir_all(&second).unwrap();
        fs::write(first.join("claude"), "not executable").unwrap();
        fs::write(second.join("claude"), "#!/bin/sh\n").unwrap();
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            fs::set_permissions(second.join("claude"), fs::Permissions::from_mode(0o700)).unwrap();
        }
        let joined = std::env::join_paths([&first, &second]).unwrap();
        assert_eq!(
            find_executable("claude", Some(&joined)),
            Some(second.join("claude"))
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn missing_path_finds_nothing() {
        assert!(find_executable("claude", None).is_none());
    }
}
